config/routes.rb
Rails.application.routes.draw do
  root "forecasts#index"

  resources :forecasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  validates :name, :latitude, :longitude, presence: true

  attr_writer :periods
  def periods
    # A hugely mild and crude means of trying to help the template not explode
    # when the weather API doesn't properly return results since I don't have
    # robust error handling there at the moment
    @periods ||= []
  end
end

app/models/weather_api.rb
# frozen_string_literal: true

# Utilizing the National Weather Service API
# https://www.weather.gov/documentation/services-web-api
#
# https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast
# https://www.weather.gov/documentation/services-web-api#/default/point
#
# Using Faraday to fetch the API data.
# https://lostisland.github.io/faraday/usage/
# https://lostisland.github.io/faraday/adapters/testing
module WeatherApi
  class Client
    def initialize(connection = nil)
      # Set the User-Agent per the National Weather Service API requirements
      @connection = connection || Faraday.new(headers: { "User-Agent": Rails.application.credentials.nws_user_agent })
    end

    def get_forecast(location)
      point_response = @connection.get("https://api.weather.gov/points/#{location.latitude},#{location.longitude}")

      # FIXME: Handle errors. We're not robust at the moment.
      #  Consider approach from
      #  https://www.nopio.com/blog/how-to-create-an-api-wrapper-of-an-external-service-in-rails/
      if point_response.success?
        forecast_api_url = parse_response_to_struct(point_response).properties.forecast
        forecast_response = @connection.get(forecast_api_url)
        forecast_response.success? ? parse_forecast_periods(forecast_response) : []
      else
        []
      end
    end

    private
      def parse_response_to_struct(response)
        JSON.parse(response.body, object_class: OpenStruct)
      end

      def parse_forecast_periods(forecast_response)
        forecast = parse_response_to_struct(forecast_response)

        # Each day in the forecast has two periods, an early one (e.g., morning, afternoon)
        # and a late one (e.g., evening). Group by the date to create tuples of these periods
        # and then wrap them within a ForecastPeriod adapter
        forecast.properties.periods
          .group_by { |period| Date.parse(period.startTime) }
          .map do |day_periods|
            now, later = day_periods.second
            ForecastPeriod.new(now, later)
          end
      end
  end

  class ForecastPeriod
    attr_accessor :first, :second

    def day
      Date.parse(@first.startTime).strftime("%A")
    end

    def high_temperature
      check_temperature { @first.temperature > @second.temperature }
    end

    def low_temperature
      check_temperature { @first.temperature < @second.temperature }
    end

    def only_one_part?
      second.nil?
    end

    private
      def initialize(first, second)
        @first = first
        @second = second
      end

      def check_temperature
        if only_one_part? || yield
          @first.temperature
        else
          @second.temperature
        end
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: %i[ show edit update destroy ]

  def index
    @forecasts = Forecast.all
  end

  def show
    client = WeatherApi::Client.new
    @forecast.periods = client.get_forecast(@forecast)
  end

  def new
    @forecast = Forecast.new
  end

  def edit
  end

  def create
    @forecast = Forecast.new(forecast_params)

    if @forecast.save
      redirect_to forecast_url(@forecast), notice: "Forecast was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @forecast.update(forecast_params)
      redirect_to forecast_url(@forecast), notice: "Forecast was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @forecast.destroy

    redirect_to forecasts_url, notice: "Forecast was successfully removed."
  end

  private
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    def forecast_params
      params.require(:forecast).permit(:name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_forecast.html.erb
<div id="<%= dom_id forecast %>">
  <p>
    <strong>Location:</strong>
    <%= forecast.name %>
    <br>
    <small>Lat: <%= forecast.latitude %>, Lng: <%= forecast.longitude %></small>
  </p>
</div>

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast, data: {
  'controller': 'place-search',
  'place-search-api-key-value': "#{Rails.application.credentials.mapquest_api_key}"
}) do |form| %>
  <% if forecast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
        <% forecast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <input type="search" data-place-search-target="search" aria-label="Search for location" placeholder="Search for location..."/>

  <%# TODO: Is there are helper for the data-*-target options?  %>
  <%= form.hidden_field :name, data: { 'place-search-target': 'name' } %>
  <%= form.hidden_field :latitude, data: { 'place-search-target': 'latitude' }  %>
  <%= form.hidden_field :longitude, data: { 'place-search-target': 'longitude' }   %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h2>Editing forecast</h2>

<%= render "form", forecast: @forecast %>

<br>

<div>
  <%= link_to "Show this forecast", @forecast %> |
  <%= link_to "Back to forecasts", forecasts_path %>
</div>

app/views/forecasts/index.html.erb
<% if notice %>
<p style="color: green"><%= notice %></p>
<% end %>

<div id="forecasts">
  <% @forecasts.each do |forecast| %>
    <%= render forecast %>
    <p>
      <%= link_to "Show this forecast", forecast %>
    </p>
  <% end %>
</div>

<%= link_to "Add forecast", new_forecast_path %>

app/views/forecasts/new.html.erb
<h2>New forecast</h2>

<%= render "form", forecast: @forecast %>

<br>

<div>
  <%= link_to "Back to forecasts", forecasts_path %>
</div>

app/views/forecasts/show.html.erb
<% if notice %>
  <p style="color: green"><%= notice %></p>
<% end %>

<%= render @forecast %>

<% if @forecast.periods.empty? %>
  <p><strong>Unable to retrieve the forecast at this time. Please try again later.</strong></p>
<% else %>
  <table>
    <% @forecast.periods.each do |period| %>
      <tr>
        <td><strong><%= period.day %></strong></td>
        <% if period.only_one_part? %>
          <td colspan="2"><%= period.high_temperature %>&deg;</td>
          <td>
            <%= period.first.name %>: <%= period.first.shortForecast %>
          </td>
        <% else %>
          <td>High: <%= period.high_temperature %>&deg;</td>
          <td>Low: <%= period.low_temperature %>&deg;</td>
          <td>
            <%= period.first.name %>: <%= period.first.shortForecast %>
            <br>
            <%= period.second.name %>: <%= period.second.shortForecast %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<div>
  <%= link_to "Edit this forecast", edit_forecast_path(@forecast) %> |
  <%= link_to "Back to forecasts", forecasts_path %>

  <%= button_to "Destroy this forecast", @forecast, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyGazer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

    <%# TODO: What is the "rails way" in bring these in and use them?
         - Perhaps a partial answer for the JS side of things: https://github.com/rails/importmap-rails
         - Now for the CSS?
         - Ditto ditto SimpleCss above
    %>
    <script src="https://api.mqcdn.com/sdk/place-search-js/v1.0.0/place-search.js"></script>
    <link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/place-search-js/v1.0.0/place-search.css"/>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <head>
     <h1>Sky Gazer</h1>
   </head>

   <%= yield %>
  </body>
</html>